import { PageHeader } from "@/components/common/page-layout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Field, FieldContent, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldTitle } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Spinner } from "@/components/ui/spinner";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowLeft, Save } from "lucide-react";
import { useMemo } from "react";
import { Controller, useForm } from "react-hook-form";
import { useTranslation } from "react-i18next";
import type { MasterRecord } from "../../api/masters-reference.api";
import { createOfficerSchema, DEFAULT_OFFICER_VALUES, type OfficerFormValues } from "./officer-schema";

export function OfficerForm({ defaultValues = DEFAULT_OFFICER_VALUES, mode = "create", organizations, lockedOrganizationCode, onCancel, onSubmit }: {
  defaultValues?: OfficerFormValues; mode?: "create" | "edit"; organizations: MasterRecord[];
  lockedOrganizationCode?: string;
  onCancel: () => void; onSubmit: (values: OfficerFormValues) => Promise<void>;
}) {
  const { t } = useTranslation("common");
  const officerSchema = useMemo(() => createOfficerSchema(t), [t]);
  const { control, formState: { errors, isSubmitting }, handleSubmit, register } = useForm<OfficerFormValues>({ defaultValues, mode: "onSubmit", reValidateMode: "onChange", resolver: zodResolver(officerSchema) });
  const lockedOrganization = organizations.find((record) => String(record.organization_code) === lockedOrganizationCode);
  return <form className="mx-auto w-full max-w-xl" noValidate onSubmit={handleSubmit(onSubmit)}><Card><CardHeader className="sr-only"><CardTitle>{t(mode === "create" ? "pages.sourcesMinistries.createOfficerTitle" : "pages.sourcesMinistries.editOfficerTitle")}</CardTitle><CardDescription>{t("pages.sourcesMinistries.officerForm.formDescription")}</CardDescription></CardHeader><CardContent className="flex flex-col gap-5"><FieldGroup>
    {lockedOrganizationCode ? <Field className="gap-1"><FieldLabel htmlFor="officer-source">{t("pages.sourcesMinistries.officerForm.fields.source")} <span className="text-destructive" aria-hidden="true">*</span></FieldLabel><Input id="officer-source" readOnly aria-required="true" value={`${String(lockedOrganization?.name ?? lockedOrganizationCode)} (${lockedOrganizationCode})`} /><input type="hidden" {...register("organization_code")} /><FieldDescription>{t("pages.sourcesMinistries.officerForm.lockedSourceHelp")}</FieldDescription><FieldError>{errors.organization_code?.message}</FieldError></Field> : <Controller control={control} name="organization_code" render={({ field }) => <Field className="gap-1" data-invalid={Boolean(errors.organization_code)}><FieldLabel htmlFor="officer-source-select">{t("pages.sourcesMinistries.officerForm.fields.source")} <span className="text-destructive" aria-hidden="true">*</span></FieldLabel><Select aria-label={t("pages.sourcesMinistries.officerForm.fields.source")} selectedKey={field.value || null} isDisabled={isSubmitting || mode === "edit"} onSelectionChange={(key) => field.onChange(String(key))}><SelectTrigger id="officer-source-select" aria-invalid={Boolean(errors.organization_code)} aria-required="true"><SelectValue /></SelectTrigger><SelectContent>{organizations.map((record) => { const code = String(record.organization_code); return <SelectItem id={code} key={code}>{String(record.name ?? code)} ({code})</SelectItem>; })}</SelectContent></Select><FieldDescription>{t(mode === "edit" ? "pages.sourcesMinistries.officerForm.sourceEditHelp" : "pages.sourcesMinistries.officerForm.sourceCreateHelp")}</FieldDescription><FieldError>{errors.organization_code?.message}</FieldError></Field>} />}
    <Field className="gap-1" data-invalid={Boolean(errors.officer_code)}><FieldLabel htmlFor="officer-code">{t("pages.sourcesMinistries.officerForm.fields.code")} <span className="text-destructive" aria-hidden="true">*</span></FieldLabel><Input id="officer-code" placeholder={t("pages.sourcesMinistries.officerForm.placeholders.code")} readOnly={mode === "edit"} aria-invalid={Boolean(errors.officer_code)} aria-required="true" disabled={isSubmitting} {...register("officer_code")} /><FieldDescription>{t(mode === "edit" ? "pages.sourcesMinistries.officerForm.codeEditHelp" : "pages.sourcesMinistries.officerForm.codeCreateHelp")}</FieldDescription><FieldError>{errors.officer_code?.message}</FieldError></Field>
    <Field className="gap-1" data-invalid={Boolean(errors.display_name)}><FieldLabel htmlFor="officer-name">{t("pages.sourcesMinistries.officerForm.fields.name")} <span className="text-destructive" aria-hidden="true">*</span></FieldLabel><Input id="officer-name" autoFocus placeholder={t("pages.sourcesMinistries.officerForm.placeholders.name")} aria-invalid={Boolean(errors.display_name)} aria-required="true" disabled={isSubmitting} {...register("display_name")} /><FieldError>{errors.display_name?.message}</FieldError></Field>
      <Field className="gap-1" data-invalid={Boolean(errors.designation)}><FieldLabel htmlFor="officer-designation">{t("pages.sourcesMinistries.officerForm.fields.designation")}</FieldLabel><Input id="officer-designation" placeholder={t("pages.sourcesMinistries.officerForm.placeholders.designation")} aria-invalid={Boolean(errors.designation)} disabled={isSubmitting} {...register("designation")} /><FieldError>{errors.designation?.message}</FieldError></Field>
      <Field className="gap-1" data-invalid={Boolean(errors.email)}><FieldLabel htmlFor="officer-email">{t("pages.sourcesMinistries.officerForm.fields.email")}</FieldLabel><Input id="officer-email" type="email" placeholder={t("pages.sourcesMinistries.officerForm.placeholders.email")} aria-invalid={Boolean(errors.email)} disabled={isSubmitting} {...register("email")} /><FieldError>{errors.email?.message}</FieldError></Field>
      <Field className="gap-1" data-invalid={Boolean(errors.mobile_number)}><FieldLabel htmlFor="officer-mobile">{t("pages.sourcesMinistries.officerForm.fields.mobile")}</FieldLabel><Input id="officer-mobile" type="tel" placeholder={t("pages.sourcesMinistries.officerForm.placeholders.mobile")} aria-invalid={Boolean(errors.mobile_number)} disabled={isSubmitting} {...register("mobile_number")} /><FieldError>{errors.mobile_number?.message}</FieldError></Field>
  </FieldGroup>{mode === "edit" ? <FieldGroup><Controller control={control} name="is_active" render={({ field }) => <FieldLabel><Field orientation="horizontal"><Checkbox isDisabled={isSubmitting} isSelected={field.value} onBlur={field.onBlur} onChange={field.onChange} /><FieldContent><FieldTitle>{t("pages.sourcesMinistries.officerForm.fields.active")}</FieldTitle><FieldDescription>{t("pages.sourcesMinistries.officerForm.activeHelp")}</FieldDescription></FieldContent></Field></FieldLabel>} /></FieldGroup> : null}</CardContent><CardFooter className="justify-end gap-2 border-t"><Button type="button" variant="outline" isDisabled={isSubmitting} onPress={onCancel}>{t("pages.sourcesMinistries.cancel")}</Button><Button type="submit" isDisabled={isSubmitting}>{isSubmitting ? <Spinner data-icon="inline-start" aria-hidden="true" /> : <Save data-icon="inline-start" aria-hidden="true" />}{t(isSubmitting ? mode === "create" ? "pages.sourcesMinistries.officerForm.creating" : "pages.sourcesMinistries.officerForm.saving" : mode === "create" ? "pages.sourcesMinistries.officerForm.create" : "pages.sourcesMinistries.officerForm.save")}</Button></CardFooter></Card></form>;
}

export function OfficerPageHeading({ title, description, onBack }: { title: string; description: string; onBack: () => void }) {
  const { t } = useTranslation("common");
  return <div className="mx-auto flex w-full max-w-xl flex-col gap-3"><Button className="w-fit" type="button" variant="outline" onPress={onBack}><ArrowLeft data-icon="inline-start" aria-hidden="true" />{t("pages.sourcesMinistries.back")}</Button><PageHeader><div><h2>{title}</h2><p>{description}</p></div></PageHeader></div>;
}
